### ISSUE TITLE
Add challenges

### ISSUE THREAD

**Issue by kylapif** [presidential-innovation-fellows/hack-the-paygap#38]
Tools for Workers 
How might we build tools to increase salary transparency in the workplace to help women better negotiate salaries and benefits?
How might we build tools to help women better negotiate their pay?
How might we build tools to help workers in an industry or at an organization collaborate to increase pay transparency in their sector or their workplace?

Tools for Companies 
How might we build tools to help companies evaluate the prevalence of gender segregation in their workforce?
How might we provide tools for companies to conduct a blind application screening process?
How might we build tools that reduce the structural need for worker negotiation?

Tools for the Public
How might we demonstrate the root causes and consequences of the gender pay gap to the broader public?
How might we demonstrate the true value of unpaid care work?
How might we bring transparency to the companies doing the most to eliminate the pay gap?
How might we demonstrate the paygap across industries, geographies, education level, and race?

**Comment by bwillman** [comment]
Updated, and pushed live.
