### ISSUE TITLE
Add Event Link

### ISSUE THREAD

**Issue by kylapif** [presidential-innovation-fellows/hack-the-paygap#39]
Add "Join us at an event" 
and link to event rsvp in community section next to github button
https://hackthepaygap.splashthat.com/

**Comment by bwillman** [comment]
Link has been added and tested.

**Comment by kylapif** [comment]
thanks ben! just tested as well and all good!

On Thu, May 5, 2016 at 7:36 PM, Ben Willman notifications@github.com
wrote:

> Link has been added and tested.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/presidential-innovation-fellows/hack-the-paygap/issues/39#issuecomment-217310165

## 

@kyla fullenwider https://twitter.com/KylaFullenwider | presidential
innovation fellow http://www.whitehouse.gov/innovationfellows
